apiVersion: v1
kind: Secret
metadata:
  name: default-secret
  namespace: kube-system
  annotations:
    # there is service named "default" in the namespace "kube-system"
    # we create a token for this service account
    kubernetes.io/service-account.name: default
# the token is only valid for 1 hour (kubectl), if we create token like this approach, it will be valid for ever
type: kubernetes.io/service-account-token # token has to be created manually, it is created automatically by k8s in previous versions
# kubectl create token default -n kube-system
